### ISSUE TITLE
armeabi系列的包只有V7，可以完善一下吗，谢谢

### ISSUE THREAD

**Issue by zhuoshirong** [microshow/RxFFmpeg#10]

**Comment by microshow** [comment]
目前暂无计划编译其他平台的so，如后续比较多人要求，则会提供其他平台so库，不过目前v7平台已经可以覆盖大部分设备了，很多大型音视频app也是仅包含v7的so。

**Comment by tianshaokai** [comment]
很需要x86和x86 64 还有v8a 的

**Comment by zhuoshirong** [comment]
嗯，谢谢，我试一下V1.0.1的SO库打包看下，后期有考虑增加FFPEG录制吗，问问您

**Comment by androidGhost** [comment]
arm64-v8a也是很有必要的，希望作者大大能抽空实现一下，非常感谢

**Comment by basillee** [comment]
想要armeabi 包

**Comment by androidGhost** [comment]
64位的包，arm64-v8a

**Comment by Waychel** [comment]
需要 arm64-v8a的

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
@zhuoshirong @tianshaokai @androidGhost @basillee 近期会提供arm-v8a的支持，感谢大家支持！

**Comment by microshow** [comment]
已支持，更新到最新版即可

**Comment by jiasijiedajidali** [comment]
> 已支持，更新到最新版即可

能不能提供下armeabi
