### ISSUE TITLE
您好,执行这个命令为什么没有作用? (急)

### ISSUE THREAD

**Issue by LinTaoAndroid** [microshow/RxFFmpeg#103]
您好: 
      我在执行从本地.mp4文件中提取音频文件,命令如下:
      "ffmpeg -i {localVideoPath} -acodec copy -y -vn {outMusicpath}"
      其中:
      localVideoPath= "/storage/emulated/0/app/video/V1019111414000000805"
      outMusicpath= "/storage/emulated/0/app/audio/V1019111414000000805.mp3"
    执行本命令没有任何反应... 回调我也打印出来了,什么也没有
   我本来是用RxFFmpegCommandList 拼接的命令,但是里面多加了字符: 
    this.add("ffmpeg");
    this.add("-y");
然后我用的是: 
  public static String[] splictMusicOrder(String inVideoPath, String outMusicPath) {
        List<String> cmdlist = new ArrayList<>();
        cmdlist.add("ffmpeg ");
        cmdlist.add("-i ");
        cmdlist.add("{");
        cmdlist.add(inVideoPath);
        cmdlist.add("} ");
        cmdlist.add("-acodec ");
        cmdlist.add("copy ");
        cmdlist.add("-y ");
        cmdlist.add("-vn ");
        cmdlist.add("{");
        cmdlist.add(outMusicPath);
        cmdlist.add("} ");
        return build(cmdlist);
    }

    public static String[] build(List<String> cmdlist) {
        String[] command = new String[cmdlist.size()];
        for (int i = 0; i < cmdlist.size(); i++) {
            command[i] = cmdlist.get(i);
        }
        return command;
    }
麻烦大神给看看,为什么执行此命令会没有任何反应,谢谢了

**Comment by microshow** [comment]
你的命令有问题吧  不需要{}

**Comment by LinTaoAndroid** [comment]
去掉{}也是无法执行...   在网上重新找了一个ffmpeg提取音频的命令也是无法执行...

**Comment by microshow** [comment]
要不就是你视频的音频编码格式问题  换个视频试试

**Comment by yangfeng1994** [comment]
-i /storage/emulated/0/DCIM/Camera/3760da75ba01162359a3bc938f386821.mp4 -f mp3 -vn /storage/emulated/0/Android/data/com.android.mvideo.tools/cache/extractAudio_2019_12_13_18_27_38.aac

用这个命令就可以了

**Comment by LinTaoAndroid** [comment]
谢谢谢谢
