### ISSUE TITLE
能不能上传一下jni ,谢谢

### ISSUE THREAD

**Issue by happyonedayforme** [microshow/RxFFmpeg#11]

**Comment by microshow** [comment]
后续相对完善稳定后，编译脚本及JNI层代码，全部上传。

**Comment by billsinla** [comment]
> 后续相对完善稳定后，编译脚本及JNI层代码，全部上传。
赞赞赞赞赞！！！

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
