### ISSUE TITLE
vivo S5、三星S7 合成背景音乐闪退

### ISSUE THREAD

**Issue by lmxjw3** [microshow/RxFFmpeg#113]
在其他手机上没问题，在这俩手机上必现闪退：
"ffmpeg -y -i " + videoPath + " -i " + curMusicPath + " -filter_complex " +
                    "[0:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=" + currentVideoVolume / 100f + "[a0];" +
                    "[1:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=" + currentMusicVolume / 100f + ",aloop=loop=-1:size=2e+09[a1];" +
                    "[a0][a1]amix=inputs=2:duration=first[aout] -map [aout] -ac 2 -c:v copy -map 0:v:0 -preset superfast " + videoAudioMakePath;

Bugly日志：

1 #00 pc 0001fe30 /data/app/com.ypt.jing-zuIin_Z7H19eUM5h4cDn8Q==/lib/arm/librxffmpeg-invoke.so [armeabi-v7a]
--
2 #01 pc 0001f7b9 /data/app/com.ypt.jing-zuIin_Z7H19eUM5h4cDn8Q==/lib/arm/librxffmpeg-invoke.so [armeabi-v7a]
3 #02 pc 0001f543 /data/app/com.ypt.jing-zuIin_Z7H19eUM5h4cDn8Q==/lib/arm/librxffmpeg-invoke.so (ffmpeg_parse_options+98) [armeabi-v7a]
4 #03 pc 00011e45 /data/app/com.ypt.jing-zuIin_Z7H19eUM5h4cDn8Q==/lib/arm/librxffmpeg-invoke.so (run_ffmpeg_command+180) [armeabi-v7a]
5 #04 pc 0001164f /data/app/com.ypt.jing-zuIin_Z7H19eUM5h4cDn8Q==/lib/arm/librxffmpeg-invoke.so (Java_io_microshow_rxffmpeg_RxFFmpegInvoke_runFFmpegCmd+134) [armeabi-v7a]
6 #05 pc 001243bd /data/app/com.ypt.jing-zuIin_Z7H19eUM5h4cDn8Q==/oat/arm/base.odex (oatexec+410557) [armeabi]
7 java:
8 io.microshow.rxffmpeg.RxFFmpegInvoke.runFFmpegCmd(Native Method)
9 io.microshow.rxffmpeg.RxFFmpegInvoke$1.run(RxFFmpegInvoke.java:59)
10 java.lang.Thread.run(Thread.java:764)

**Comment by microshow** [comment]
这两台机子所有命令都执行不了吗？

**Comment by lmxjw3** [comment]
> 这两台机子所有命令都执行不了吗？

抱歉，今天拿到客户的手机了，测试了一下是文件不存在的问题，真的抱歉
