### ISSUE TITLE
视频裁剪命令，同样的语句windows版FFmpeg几乎精确，这个框架裁出来的严重不正确

### ISSUE THREAD

**Issue by silladus** [microshow/RxFFmpeg#117]
裁5秒出来17秒，电脑上误差只有1秒
下面是命令行：
ffmpeg -ss 13 -t 4 -accurate_seek -i input.mp4 -codec copy -avoid_negative_ts 1 output.mp4

是bug还是Android平台不行？

**Comment by microshow** [comment]
可以试下这个命令  ffmpeg -y -ss 00:00:00 -t 00:00:05 -i /storage/emulated/0/1/input.mp4 -codec copy /storage/emulated/0/1/result.mp4

**Comment by silladus** [comment]
> 可以试下这个命令 ffmpeg -y -ss 00:00:00 -t 00:00:05 -i /storage/emulated/0/1/input.mp4 -codec copy /storage/emulated/0/1/result.mp4

这样是没问题的，但这个是从0开始截，我想从第13秒开始截。
试过好几次，我那条指令有时误差很大，有时又接近精确，所以我关闭了这个Issues
