### ISSUE TITLE
运行runCommandRxJava崩溃

### ISSUE THREAD

**Issue by gleon123** [microshow/RxFFmpeg#119]
03-09 10:32:49.838 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG: ffmpeg version 4.0
03-09 10:32:49.838 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:  Copyright (c) 2000-2018 the FFmpeg developers
03-09 10:32:49.838 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   built with gcc 4.9.x (GCC) 20150123 (prerelease)
03-09 10:32:49.838 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv8-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android- --target-os=android --arch=arm64 --cpu=armv8-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-21/arch-arm64/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enable-decode
03-09 10:32:49.838 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   WARNING: library configuration mismatch
03-09 10:32:49.838 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avutil      configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
03-09 10:32:49.838 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avcodec     configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
03-09 10:32:49.838 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avformat    configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avdevice    configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avfilter    configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   swscale     configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   swresample  configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   postproc    configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavutil      56. 14.100 / 56. 14.100
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavcodec     58. 18.100 / 58. 18.100
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavformat    58. 12.100 / 58. 12.100
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavdevice    58.  3.100 / 58.  3.100
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavfilter     7. 16.100 /  7. 16.100
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libswscale      5.  1.100 /  5.  1.100
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libswresample   3.  1.100 /  3.  1.100
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libpostproc    55.  1.100 / 55.  1.100
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app D/TAG_FFMPEG: Splitting the commandline.
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app D/TAG_FFMPEG: Reading option '-y' ...
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app D/TAG_FFMPEG:  matched as option 'y' (overwrite output files) with argument '1'.
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app D/TAG_FFMPEG: Reading option '-i' ...
03-09 10:32:49.848 2213-2314/io.microshow.rxffmpeg.app A/libc: Fatal signal 11 (SIGSEGV) at 0x0000000c (code=1), thread 2314 (RxCachedThreadS)

**Comment by microshow** [comment]
v2.3.0
1、提升SDK健壮性；
2、修复连续执行命令可能导致闪退的问题（比如执行完A命令立马执行B命令）；
3、修复执行中断命令动作后立马执行下一个命令导致闪退的问题；

**Comment by jhwsx** [comment]
@microshow ，我这边也遇到了这个问题。

**Comment by microshow** [comment]
> @microshow ，我这边也遇到了这个问题。

命令发一下;升级到最新版试试
