### ISSUE TITLE
作者可否讲讲库中进度的计算方法，我看了一眼代码没看懂

### ISSUE THREAD

**Issue by tianshaokai** [microshow/RxFFmpeg#12]

**Comment by microshow** [comment]
计算方法是在ndk层去处理的，java层只接收结果~
拿到视频总长度，和当前处理的长度，即可计算出实际进度。

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/51720755-d5bc3300-2089-11e9-9de7-89f993edbc54.png)
目前代码中看不出来你的进度是从ndk中取出来的

**Comment by tianshaokai** [comment]
哈哈什么时候看看作者的jni方法啊

**Comment by microshow** [comment]
哈哈 ，目前正在做下一版，后续稳定后，全部上传，敬请期待噢~~~

**Comment by tianshaokai** [comment]
嗯，要是能有命名函数的使用demo就好了，我更希望使用命令来学习ffmpeg，

**Comment by microshow** [comment]
后续会补充常用的命令的 ，比如裁剪、拼接、背景音乐、字母、贴纸等等一系列~~

**Comment by tianshaokai** [comment]
太棒了期待学习

**Comment by tianshaokai** [comment]
我也以前在mac上编译ffmpeg 最新版一直没有成功，到时候试试作者的脚本

**Comment by wp292519413** [comment]
> ![image](https://user-images.githubusercontent.com/6706496/51720755-d5bc3300-2089-11e9-9de7-89f993edbc54.png)
> 目前代码中看不出来你的进度是从ndk中取出来的

可以参考这个文章
https://blog.csdn.net/yhaolpz/article/details/78350435

**Comment by online2** [comment]
> > ![image](https://user-images.githubusercontent.com/6706496/51720755-d5bc3300-2089-11e9-9de7-89f993edbc54.png)
> > 目前代码中看不出来你的进度是从ndk中取出来的
> 
> 可以参考这个文章
> https://blog.csdn.net/yhaolpz/article/details/78350435

**Comment by online2** [comment]
求问视频压缩的关键词是那个？用了参考文章的方法，执行一小段时间 strstr()就会导致app挂了。

**Comment by microshow** [comment]
ffmpeg -y -i /storage/emulated/0/1/input.mp4 -b 2097k -r 30 -vcodec libx264 -preset superfast /storage/emulated/0/1/result.mp4

**Comment by microshow** [comment]
@online2

**Comment by online2** [comment]
谢谢，，我是想了解，在执行视频压缩的过程中，作者采用的进度获取的方式是什么的逻辑？是通过ffmpeg的log去截取吗？还是其他方式？我采用了https://blog.csdn.net/yhaolpz/article/details/78350435这篇文章的逻辑，去出来，执行一段时间，在strstr()去获取 time=的时候，会挂掉。

**Comment by microshow** [comment]
@online2 你发的那篇文章不是我写的哦，在ffmpeg.c里面去修改的，拿到视频总长度，和当前处理的长度，即可计算出实际进度。

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
