### ISSUE TITLE
代码和Demo，gradle库 都非常难下载

### ISSUE THREAD

**Issue by tomguan** [microshow/RxFFmpeg#122]
速度非常慢，老是提示失败。是不是我网络问题

**Comment by microshow** [comment]
大多数是网络问题 试着切换下网络

**Comment by microshow** [comment]
v2.3.0
1、提升SDK健壮性；
2、修复连续执行命令可能导致闪退的问题（比如执行完A命令立马执行B命令）；
3、修复执行中断命令动作后立马执行下一个命令导致闪退的问题；
