### ISSUE TITLE
Fatal signal 11 (SIGSEGV) at 0x0000000b (code=1), thread 6278 (RxCachedThreadS)

### ISSUE THREAD

**Issue by gleon123** [microshow/RxFFmpeg#128]
04-13 10:09:20.864 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG: ffmpeg version 4.0
04-13 10:09:20.864 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:  Copyright (c) 2000-2018 the FFmpeg developers
04-13 10:09:20.864 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   built with gcc 4.9.x (GCC) 20150123 (prerelease)
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv8-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android- --target-os=android --arch=arm64 --cpu=armv8-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-21/arch-arm64/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enable-decode
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   WARNING: library configuration mismatch
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avutil      configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avcodec     configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avformat    configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avdevice    configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   avfilter    configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   swscale     configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   swresample  configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   postproc    configuration: --prefix=/mnt/d/DevConfig/ffmpeg/4.0/build/build_script/lib/ffmpeg/armv7-a --enable-neon --enable-hwaccels --enable-nonfree --enable-gpl --enable-x86asm --disable-shared --enable-static --cross-prefix=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --arch=arm --cpu=armv7-a --cc=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --nm=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm --enable-cross-compile --sysroot=/mnt/d/DevConfig/ffmpeg/ndk/android-ndk-r14b/platforms/android-16/arch-arm/ --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfdk-aac --enable-encoder=libfdk_aac --enable-encoder=aac --enable-encoder=mjpeg --enable-encoder=png --enable-encoder=gif --enabl
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavutil      56. 14.100 / 56. 14.100
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavcodec     58. 18.100 / 58. 18.100
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavformat    58. 12.100 / 58. 12.100
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavdevice    58.  3.100 / 58.  3.100
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libavfilter     7. 16.100 /  7. 16.100
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libswscale      5.  1.100 /  5.  1.100
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libswresample   3.  1.100 /  3.  1.100
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app I/TAG_FFMPEG:   libpostproc    55.  1.100 / 55.  1.100
04-13 10:09:20.874 1456-2095/io.microshow.rxffmpeg.app A/libc: Fatal signal 11 (SIGSEGV) at 0x0000000c (code=1), thread 2095 (RxCachedThreadS)
04-13 10:09:20.974 157-157/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-13 10:09:20.974 157-157/? I/DEBUG: Build fingerprint: 'Xiaomi/sagit/sagit:4.4.2/NMF26X/381181204:user/release-keys'
04-13 10:09:20.974 157-157/? I/DEBUG: Revision: '0'
04-13 10:09:20.974 157-157/? I/DEBUG: pid: 1456, tid: 2095, name: RxCachedThreadS  >>> io.microshow.rxffmpeg.app <<<
04-13 10:09:20.974 157-157/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000000c
04-13 10:09:21.014 157-157/? I/DEBUG:     eax 0000000c  ebx 000000c6  ecx 0000000c  edx 0000000c
04-13 10:09:21.014 157-157/? I/DEBUG:     esi 00000e59  edi 00000000
04-13 10:09:21.014 157-157/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000043  xss 0000007b
04-13 10:09:21.014 157-157/? I/DEBUG:     eip 7e63a966  ebp 1a123f2c  esp 1a123ee4  flags 00210246
04-13 10:09:21.014 157-157/? I/DEBUG: backtrace:
04-13 10:09:21.014 157-157/? I/DEBUG:     #00  pc 000c6966  /system/lib/libhoudini.so
04-13 10:09:21.014 157-157/? I/DEBUG:     #01  pc 0000e1bf  <unknown>
04-13 10:09:21.014 157-157/? I/DEBUG:     #02  pc 000b2212  /system/lib/libhoudini.so
04-13 10:09:21.014 157-157/? I/DEBUG:     #03  pc 0000e02f  <unknown>
04-13 10:09:21.014 157-157/? I/DEBUG:     #04  pc 000aeea7  /system/lib/libhoudini.so
04-13 10:09:21.014 157-157/? I/DEBUG:     #05  pc 00012643  /system/lib/arm/libc.so
04-13 10:09:21.014 157-157/? I/DEBUG:     #06  pc 000ae88c  /system/lib/libhoudini.so
04-13 10:09:21.014 157-157/? I/DEBUG:     #07  pc ffffffff  <unknown>
04-13 10:09:21.014 157-157/? I/DEBUG:     #08  pc 000fdb2c  /system/lib/libhoudini.so
04-13 10:09:21.014 157-157/? I/DEBUG: stack:
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ea4  00000001  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ea8  00000000  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123eac  00000002  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123eb0  00000000  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123eb4  000002f6  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123eb8  1a112030  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ebc  1a123f2c  [stack:2095]
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ec0  7e6272ee  /system/lib/libhoudini.so
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ec4  1a112030  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ec8  e938f7fd  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ecc  1660e8d6  /data/app-lib/io.microshow.rxffmpeg.app-2/librxffmpeg-invoke.so
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ed0  1a112030  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ed4  00000473  
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ed8  1660e8da  /data/app-lib/io.microshow.rxffmpeg.app-2/librxffmpeg-invoke.so
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123edc  1a123f2c  [stack:2095]
04-13 10:09:21.014 157-157/? I/DEBUG:          1a123ee0  7e63cf59  /system/lib/libhoudini.so
04-13 10:09:21.014 157-157/? I/DEBUG:     #00  1a123ee4  1a1121c0  
04-13 10:09:21.014 157-157/? I/DEBUG:          ........  ........
04-13 10:09:21.014 157-157/? I/DEBUG:          ........  ........
04-13 10:09:21.014 157-157/? I/DEBUG:     #02  1a123f34  1a112030  
04-13 10:09:21.014 157-157/? I/DEBUG:          ........  ........

**Comment by gleon123** [comment]
android4.x的系统还是会崩溃

**Comment by microshow** [comment]
你的是4点几的系统，
我手上一台4.4.2的目前运行没问题，可能4.x的部分系统有问题，不过现在4.x的手机不多了吧，建议放弃4.x

**Comment by gleon123** [comment]
> 你的是4点几的系统，
> 我手上一台4.4.2的目前运行没问题，可能4.x的部分系统有问题，不过现在4.x的手机不多了吧，建议放弃4.x

夜神模拟器4.4.2不可以，一定要真机吗，我用LanSong短视频SDK怎么就可以在模拟器上跑了？
