### ISSUE TITLE
音频裁剪报转码失败，请大神帮忙看看！

### ISSUE THREAD

**Issue by ziliang520** [microshow/RxFFmpeg#129]
大神你好，我在做音频裁剪的时候，选的大部分音乐裁剪是没有问题的，但有少部分一直报转码失败，打印信息是从onError(message:String?)里面的message，我反复检查了音频文件，是没有问题的，请大神帮帮忙看看，谢谢。

我使用的指令：ffmpeg -y -i /storage/emulated/0/Android/data/包名/cache/music/1586826748621.mp3 -vn -acodec copy -ss 00:00:00 -t 00:00:13 /storage/emulated/0/Android/data/包名/cache/music/1586826743300.mp3

**Comment by microshow** [comment]
SDK什么版本；必现吗？

**Comment by ziliang520** [comment]
sdk 29的，有一两个mp3是必现的，大部分mp3文件没有这个问题，但是这个mp3文件在与视频合并是正常，只是裁剪除了这个问题。

**Comment by ziliang520** [comment]
sdk 29的，有一两个mp3是必现的，大部分mp3文件问题，而且出问题的mp3文件在与视频合并是正常，只是裁剪出了这个问题。

**Comment by ziliang520** [comment]
sdk 29的，有一两个mp3是必现的，大部分mp3文件没问题，而且出问题的mp3文件在与视频合并是正常，只是裁剪出了这个问题。

**Comment by microshow** [comment]
升级RxFFmpeg 2.4.0版本看看

**Comment by microshow** [comment]
那有没看 出问题的mp3 和没问题的mp3   有什么差异

**Comment by ziliang520** [comment]
有去做过对比，但是实在是看不出有什么区别，比较骚的是合成视频的时候是没有问题的，文件在本地也可以正常播放。就是裁剪不了。

**Comment by microshow** [comment]
-acodec libmp3lame

**Comment by ziliang520** [comment]
我尝试了您发的这个命令，命令拼成：ffmpeg -y -i $inPath -vn -acodec libmp3lame -ss $startTime -t $endTime $outPath，这个解决了我现在的问题，但运行时间加长了，比之前执行时间长了好几倍，这个有办法提高速度吗？

**Comment by microshow** [comment]
重新进行编码了，时间会长一些，-preset superfast
最好你可以动态判断该音频是否要设置重新编码

**Comment by ziliang520** [comment]
这个问题是什么原因导致的，还是说表面是mp3实际上不是？能否提供一个思路给我参考一下，我想选音乐的时候提前判断，并转码后返回，现在的问题是我不知道该如何判断，因为我不清楚为什么会导致这样的问题。

**Comment by microshow** [comment]
可能是有些音频是有封面信息的，把封面信息去除就可以
