### ISSUE TITLE
你好，请问音频裁剪，直接替换demo 中得path 就可以吗，我替换了一个.mp3 音频文件，报错为 onError:找不到输入文件

### ISSUE THREAD

**Issue by lxb89** [microshow/RxFFmpeg#13]

**Comment by microshow** [comment]
音频裁剪：-ss是开始时间;  -t是持续时长
ffmpeg -y -i /storage/emulated/0/1/input.mp3 -ss 00:00:00 -t 00:00:05 /storage/emulated/0/1/result.mp3

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by lxb89** [comment]
好的，多谢

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
