### ISSUE TITLE
集成RxFFmpeg，运行直接闪退，提示java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by qiushihang** [microshow/RxFFmpeg#130]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader
lib/armeabi-v7a, /system/lib, /hw_product/lib]]] couldn't find "librxffmpeg-core.so"

**Comment by microshow** [comment]
demo 能跑通吗

**Comment by qiushihang** [comment]
之前集成过一次，我就尝试了下期中的拼接指令，能跑通，但是今天在新项目重新依赖，发现一执行就闪退，看到日志是说找不到这个so,但是我在根目录下也配置了abiFilters "armeabi-v7a"，不知道怎么回事了

**Comment by microshow** [comment]
建议先跑下demo

**Comment by qiushihang** [comment]
这个问题rebuild 下工程就好，已解决

**Comment by microshow** [comment]
OK
