### ISSUE TITLE
旋转视频直接崩溃

### ISSUE THREAD

**Issue by fylw** [microshow/RxFFmpeg#132]
ffmpeg -y -i /storage/emulated/0/1587224574111.mp4 -filter_complex transpose=2 -preset superfast /storage/emulated/0/test.mp4

执行旋转视频命令直接崩溃了

**Comment by microshow** [comment]
> ffmpeg -y -i /storage/emulated/0/1587224574111.mp4 -filter_complex transpose=2 -preset superfast /storage/emulated/0/test.mp4
> 
> 执行旋转视频命令直接崩溃了

试了一下命令没问题，检查下你的文件是否存在，及有没开SD卡权限

**Comment by fylw** [comment]
不好意思，我把文件给删了,这个在sdk中可以在可以添加检测，素材不存在直接输出error,不要直接崩溃了

**Comment by fylw** [comment]
不好意思，我把文件给删了,这个在sdk中可以在添加检测吗，素材不存在直接输出error,不要直接崩溃了

**Comment by microshow** [comment]
建议你可以执行命令的时候 在java层先检测一下文件是否存在，后续会在完善！
