### ISSUE TITLE
简单的关于编译的问题

### ISSUE THREAD

**Issue by TpOut** [microshow/RxFFmpeg#14]
你好作者，因为公司项目库老旧需要更换
最近也在看ffmpeg编译相关的内容
但是基本没有ffmpeg4.1 + ndk 19 + clang的处理方法
想问下用以前的编译方式会在新的Android平台版本产生兼容问题吗
（因为之前的库就是这样的）

顺便问下有没有好一点的学习文章啊。我看ffmpeg和Android ndk官网都各讲各的
没有c基础的表示完全看不懂怎么把两个连接起来

**Comment by microshow** [comment]
兼容性这个就需要你自己多测测了;  可以到ffmpeg官网获取一些资料等，找一些demo之类的

**Comment by TpOut** [comment]
问下我如果从camera拿到原始数据，byte[] ，个人感觉Android的应该是yuv的，可以通过命令编码成h264格式的文件吗。
和库不是很相关，谢谢
