### ISSUE TITLE
压缩模糊

### ISSUE THREAD

**Issue by sangsais** [microshow/RxFFmpeg#147]
Android客户端

使用华为P20， 本地拍摄一段15秒短视频 ，文件大小29.17MB。

使用
"ffmpeg -y -i /storage/emulated/0/input.mp4 -vf boxblur=5:1 -preset superfast /storage/emulated/0/result.mp4"

输出的result.mp4非常模糊

请问，怎么配置参数，可以提高清晰度，另外，我压缩耗时25秒左右，这个压缩时间是正常的么？

**Comment by microshow** [comment]
boxblur，是用来处理毛玻璃效果的。

ffmpeg -y -i /storage/emulated/0/input.mp4 -preset superfast /storage/emulated/0/result.mp4

**Comment by sangsais** [comment]
感谢，直接编译跑的demo，看是这样，就没动。去掉毛玻璃配置后，清晰了。
就是时间比较久，能配置压缩比例么，我刚刚测试30M使用这个ffmpeg -y -i /storage/emulated/0/input.mp4 -preset superfast /storage/emulated/0/result.mp4，压缩后是15M,要15秒，还有办法压得更小更快么。

**Comment by microshow** [comment]
可以配置码率，帧率这些

**Comment by sangsais** [comment]
感谢
