### ISSUE TITLE
解决了我的问题，感觉这个很牛逼

### ISSUE THREAD

**Issue by woleigeququ** [microshow/RxFFmpeg#15]
thanks a lot

**Comment by microshow** [comment]
感谢支持！

**Comment by AndSync** [comment]
卡了好几天的一个命令 借助这个库找到原因了 多谢 继续学习中

**Comment by microshow** [comment]
@AndSync  感谢支持！

**Comment by AndSync** [comment]
@microshow 不过这个还不能通过gradle 方式引入吗？

**Comment by microshow** [comment]
@AndSync  后续会补充完善，敬请期待。。。

**Comment by AndSync** [comment]
@microshow 能否请教一个命令 音视频（格式mp4/mp3）合并 如果视频比音频时间长 音频循环
如果视频时间比音频短 将音频裁剪

**Comment by microshow** [comment]
1、如果视频比音频时间长 音频循环： 需要根据视频时长，事先拼接音频，保持音频时间和视频一致，可能还涉及到裁剪音频，根据实际时长处理；
2、如果视频时间比音频短 将音频裁剪：需要根据视频时长先裁剪音频，在合成

大致就这样，命令的话你得分步骤去处理了

**Comment by microshow** [comment]
@AndSync

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
@woleigeququ  @AndSync 接入RxFFmpeg的APP方便可以留下联系方式，APP名称+应用商店下载地址，（按登记顺序排序)，啦啦啦
https://github.com/microshow/RxFFmpeg/issues/37

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
