### ISSUE TITLE
希望增加更多的常用使用Demo

### ISSUE THREAD

**Issue by Liberations** [microshow/RxFFmpeg#150]
集成到项目中快速上手研发有一定周期

**Comment by microshow** [comment]
比如可以先熟悉一下命令，https://github.com/microshow/RxFFmpeg/blob/master/preview/docs/cmd.md
然后修改下输入和输出文件路径，放到RxFFmpeg执行命令即可。

**Comment by Liberations** [comment]
好的 太难了
