### ISSUE TITLE
点击视频进度条无效，只会回到初始位置0

### ISSUE THREAD

**Issue by gleon123** [microshow/RxFFmpeg#152]
如上

**Comment by microshow** [comment]
所有视频？

**Comment by gleon123** [comment]
你封装那个播放器是否有bug，我在你的demo上点击那个视频的进度条无效


 
---原始邮件---
发件人: "Super"<notifications@github.com&gt;
发送时间: 2020年5月29日(星期五) 晚上6:23
收件人: "microshow/RxFFmpeg"<RxFFmpeg@noreply.github.com&gt;;
抄送: "gleon123"<522395907@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [microshow/RxFFmpeg] 点击视频进度条无效，只会回到初始位置0 (#152)




 
所有视频？

**Comment by microshow** [comment]
视频关键帧比较少的话seek会去找附近的关键帧，所以就可能出现你说的情况
