### ISSUE TITLE
压缩视频 华为nove4 mate30pro闪退

### ISSUE THREAD

**Issue by DaWeiDavy** [microshow/RxFFmpeg#155]
压缩指令为："ffmpeg -y -i " + oriPath + " -crf 35 -vcodec libx264 -preset superfast " + outPath
这两台手机系统都是android-10的，压缩时，进度到9%然后闪退。

**Comment by microshow** [comment]
[参考下](https://github.com/microshow/RxFFmpeg/issues/51)

**Comment by DaWeiDavy** [comment]
> [参考下](https://github.com/microshow/RxFFmpeg/issues/51)

报错信息是：
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 22878 (RxCachedThreadS), pid 22386 (a.xiegoutraffic)
应该是jni层的问题

**Comment by microshow** [comment]
demo apk 试试，或者换个视频分析下

**Comment by DaWeiDavy** [comment]
> demo apk 试试，或者换个视频分析下

我这个场景是在录完屏，直接就压缩。
小米 android 10没有问题，三星 oppo android8.0都没有问题，华为6.0也没问题的，就是华为 android10出错了

**Comment by DaWeiDavy** [comment]
> demo apk 试试，或者换个视频分析下

demo apk下载下来，也会有同样的问题，闪退

**Comment by microshow** [comment]
用这个 ffmpeg -y -i /storage/emulated/0/1/input.mp4 -b 2097k -r 30 -vcodec libx264 -preset superfast /storage/emulated/0/1/result.mp4
亲测有效！

**Comment by microshow** [comment]
android 10 sd权限有变更

**Comment by DaWeiDavy** [comment]
> 用这个 ffmpeg -y -i /storage/emulated/0/1/input.mp4 -b 2097k -r 30 -vcodec libx264 -preset superfast /storage/emulated/0/1/result.mp4
> 亲测有效！

还是在华为的android10设备上闪退，小米的android 10设备上没有问题

**Comment by microshow** [comment]
在demo apk上试试

**Comment by microshow** [comment]
录屏的视频有问题？其它拍摄的视频呢

**Comment by DaWeiDavy** [comment]
> 录屏的视频有问题？其它拍摄的视频呢

只有华为的android 版本q会闪退，其他手机低版本，其他品牌android q都可以的。代码都没有变。

**Comment by microshow** [comment]
刚用了p30试了下没发现问题……

**Comment by DaWeiDavy** [comment]
> 刚用了p30试了下没发现问题……

压缩    用nova4    mate30pro都会闪退
