### ISSUE TITLE
添加背景音乐命令执行后疯狂输出日志问题

### ISSUE THREAD

**Issue by ziliang520** [microshow/RxFFmpeg#156]
![image](https://user-images.githubusercontent.com/5440361/84730072-d4b1db80-afc7-11ea-8871-15c02f5339c4.png)
我在执行了添加背景音乐后，疯狂的输出log，如图，请问这是报错了还是什么问题?

调用命令：ffmpeg -y -i /storage/emulated/0/Android/data/com.vivwe.main/cache/video/dea468bb-7558-4c7d-869f-50d0957f65eb.mp4 -i /storage/emulated/0/Android/data/com.vivwe.main/cache/music/1592279315498.mp3 -filter_complex [0:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=0[a0];[1:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=2[a1];[a0][a1]amix=inputs=2:duration=first[aout] -map [aout] -ac 2 -c:v copy -map 0:v:0 -preset superfast /storage/emulated/0/Android/data/com.vivwe.main/files/video/1592279310160.mp4

**Comment by microshow** [comment]
这个不像是RxFFmpeg输出的日志，你可以关闭日志试试 RxFFmpegInvoke.getInstance().setDebug(false);

**Comment by ziliang520** [comment]
好的，谢谢

**Comment by ziliang520** [comment]
大神你好，我经过测试了一下，发现确实是调用了一段添加背景音乐的指令后才导致日志的疯狂输出，能否帮我看看这个命令是否有什么问题，这个命令是在常用指令里面找的。
指令：ffmpeg -y -i /storage/emulated/0/Android/data/com.vivwe.main/cache/video/5efb0662-ccbf-456a-b145-6e6e6d0c3e44.mp4 -i /storage/emulated/0/Android/data/com.vivwe.main/cache/music/1592293670043.mp3 -filter_complex [0:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=0[a0];[1:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=2[a1];[a0][a1]amix=inputs=2:duration=first[aout] -map [aout] -ac 2 -c:v copy -map 0:v:0 -preset superfast /storage/emulated/0/Android/data/com.vivwe.main/files/video/1592293663725.mp4

**Comment by ziliang520** [comment]
![image](https://user-images.githubusercontent.com/5440361/84746974-42223400-afe9-11ea-8523-7ec1a5431947.png)

**Comment by microshow** [comment]
刚试了一下这个命令，没有输出这些日志， 小米手机

**Comment by microshow** [comment]
估计是你手机其它App的日志，不仿换台手机测测？

**Comment by microshow** [comment]
只要最后结果视频没问题就可以！！

**Comment by ziliang520** [comment]
视频结果是没有问题的，就是每一次调用后就会累加日志输出的速度，调用三次左右，从几次每秒会上升到三十几次每秒，我有点担心出现内存溢出。

**Comment by microshow** [comment]
嗯，最好用多台机型去测

**Comment by ziliang520** [comment]
我记得您上次给我讲过音乐里面有其他信息的问题，会不会这个也会有影响？

**Comment by ziliang520** [comment]
好的，我多拿几台试试。

**Comment by ziliang520** [comment]
这个错误前先报了一个错误：2020-06-16 16:16:43.602 25299-25798/com.vivwe.main E/MediaPlayerNative: error (-38, 0)

**Comment by ziliang520** [comment]
错误问题找到了，调用了其他同事的代码，他的mediaPlayer类播放这个文件返回来的时候没有释放导致的，感谢大神抽空帮助我。再次感谢！
