### ISSUE TITLE
想将多个图片以淡入淡出的方式生成视频，执行此命令会崩溃

### ISSUE THREAD

**Issue by wujicao** [microshow/RxFFmpeg#160]
String string = "ffmpeg " +
                "-loop 1 -t 5 -i /storage/emulated/0/magic/pictures/image1.jpg " +
                "-loop 1 -t 5 -i /storage/emulated/0/magic/pictures/image2.jpg " +
                "-loop 1 -t 5 -i /storage/emulated/0/magic/pictures/image3.jpg " +
                "-loop 1 -t 5 -i /storage/emulated/0/magic/pictures/image4.jpg " +
                "-filter_complex " +
                "[0:v]fade=t=out:st=4:d=1[v0];" +
                "[1:v]fade=t=in:st=0:d=1,fade=t=out:st=4:d=1[v1];" +
                "[2:v]fade=t=in:st=0:d=1,fade=t=out:st=4:d=1[v2];" +
                "[3:v]fade=t=in:st=0:d=1,fade=t=out:st=4:d=1[v3];" +
                "[4:v]fade=t=in:st=0:d=1,fade=t=out:st=4:d=1[v4];" +
                "[v0][v1][v2][v3][v4]concat=n=5:v=1:a=0[v] -map '[v]' /storage/emulated/0/magic/test2.mp4";
![image](https://user-images.githubusercontent.com/26382053/86456808-38bcf980-bd55-11ea-92a8-f7f6f727c780.png)

**Comment by microshow** [comment]
检查下命令

**Comment by wujicao** [comment]
还有一个问题
在设置淡入淡出的时候
cmdlist.append("fade=in:0:5:alpha=1,fade=out:25:n=5:alpha=1");
alpha和其他颜色设置貌似不生效，只有默认是可行的

这个是命令问题还是？
