### ISSUE TITLE
delogo命令出错，delogo区域明明没有超出视频宽高，却报错了

### ISSUE THREAD

**Issue by nxnyk** [microshow/RxFFmpeg#165]
![image](https://user-images.githubusercontent.com/42330422/87267463-5a0eaa00-c4fa-11ea-999c-fb80cd779330.png)
如图所示。。啥原因啊

**Comment by nxnyk** [comment]
> 完整命令看下

![image](https://user-images.githubusercontent.com/42330422/87268694-a7404b00-c4fd-11ea-88a7-9e2b24e11419.png)
完整命令。。。

**Comment by microshow** [comment]
1、建议检查下命令；
视频去水印
//x:y 离左上角的坐标 值必须>=1;  w:h logo的宽和高;  show：设为1有一个绿色的矩形边框，默认值0
ffmpeg -y -i /storage/emulated/0/1/input.mp4 -vf delogo=x=1:y=1:w=200:h=200:show=1 -preset superfast /storage/emulated/0/1/result.mp4
2、可以在demo上运行这个命令试试有没问题
3、检查文件是否存在，是否有SD权限，是否是 api 29?

**Comment by nxnyk** [comment]
小点没事  宽高 100 就可以，delogo区域稍微大一点就不行 闪退

**Comment by nxnyk** [comment]
> 1、建议检查下命令；
> 视频去水印
> //x:y 离左上角的坐标 值必须>=1; w:h logo的宽和高; show：设为1有一个绿色的矩形边框，默认值0
> ffmpeg -y -i /storage/emulated/0/1/input.mp4 -vf delogo=x=1:y=1:w=200:h=200:show=1 -preset superfast /storage/emulated/0/1/result.mp4
> 2、可以在demo上运行这个命令试试有没问题
> 3、检查文件是否存在，是否有SD权限，是否是 api 29?

小点没事 宽高 100 就可以，delogo区域稍微大一点就不行 闪退

**Comment by microshow** [comment]
不要超过视频边界

**Comment by microshow** [comment]
宽高是否正确，原始视频是否是选转的

**Comment by nxnyk** [comment]
> 宽高是否正确，原始视频是否是旋转的

旋转了会影响 宽高的判定？ 我下午尝试下是不是这个原因

**Comment by microshow** [comment]
其实你可以换个其他视频试试
