### ISSUE TITLE
您好，我这遇到倒转视频失败： cur_dts is invalid (this is harmless if it occurs once at the start per stream)

### ISSUE THREAD

**Issue by DannySparke** [microshow/RxFFmpeg#17]
如您需要问题视频，我可以提供给您。我的qq：1083857985

**Comment by DannySparke** [comment]
这是我用的命令：ffmpeg -i /storage/sdcard0/1994.mp4 -vf reverse -af areverse -preset superfast /storage/sdcard0/reversed.mp4

**Comment by microshow** [comment]
试了一下，没问题哦  ffmpeg -y -i /storage/emulated/0/1/input.mp4 -vf reverse -af areverse -preset superfast /storage/emulated/0/1/result.mp4

**Comment by DannySparke** [comment]
我这个视频时间错有问题，但使用电脑版的ffmpeg4.0能正常倒转，但是使用您编译的无法正常倒转。如果您需要验证的话，我可以给你提供原视频，感谢！！！

**Comment by microshow** [comment]
你那视频是什么样的视频，是手机拍摄的？可以共享到百度网盘上来

**Comment by DannySparke** [comment]
已上传到百度云，您帮忙看一下：https://pan.baidu.com/s/1h56ISlBDnjqnLE3QEhRFDg

**Comment by microshow** [comment]
或者 -vcodec libx264  在原有的命令上加上这个试试

**Comment by DannySparke** [comment]
加上这个也无法正常倒转

**Comment by microshow** [comment]
视频应该有点问题，在我手机上用自带的播放器都无法播放，建议在录屏的时候修改下相关参数码率桢率这些，或者试下对这个视频进行转码 然后在处理，

我试了一下我本机的视频都是可以倒叙的~

建议从源头解决问题哒~

**Comment by DannySparke** [comment]
好吧。不过感谢啦

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
