### ISSUE TITLE
视频转换为amv

### ISSUE THREAD

**Issue by z8806c** [microshow/RxFFmpeg#179]
Unable to find a suitable output format

**Comment by z8806c** [comment]
MP4转码视频
//RM转到一半奔溃Muxing packets larger than 64 kB (119574) is not supported
        //rmvb AMV文件Unable to find a suitable output format for
闪退

**Comment by microshow** [comment]
具体命令呢

**Comment by z8806c** [comment]
> 具体命令呢

ffmpeg -i 源地址 -y 新地址

MP4文件转  rm rmvb AMV 这几个会错误 闪退
加入-vcodec copy -acodec copy 也是错误

**Comment by microshow** [comment]
那有些视频格式不支持
