### ISSUE TITLE
没有native代码呀！！！

### ISSUE THREAD

**Issue by ltlovezh** [microshow/RxFFmpeg#18]
没有Native代码，这不叫开源呀...

**Comment by microshow** [comment]
嗯，等相对稳定后全面提供编译脚本及JNI层代码，
最近准备全面升级最新的FFmpeg 4.1.1版本及其它相关库的版本，敬请期待……

**Comment by microshow** [comment]
@ltlovezh

**Comment by TpOut** [comment]
@microshow 大佬你好，我想基于你这个，根据网上的教程写下yuv，pcm转mp4的代码。能不能先发一份编译后的include给我？416756910@qq.com 谢谢

**Comment by sway913** [comment]
有QQ群吗？一起探讨下吧

**Comment by microshow** [comment]
@TpOut 你直接在ffmpeg官网上下载ffmpeg include导入进去有问题吗？

**Comment by microshow** [comment]
@sway913 暂无，有问题可以先提issues

**Comment by TpOut** [comment]
@microshow 是的，你这个项目就是官方的4.0啊，我之前尝试了没有文件，后来干脆直接Include整个项目了，好像也除了什么问题，具体忘了。。
我自己编译4.1的时候，core.so 是可以使用的，但是命令行执行老是出错。。很尴尬
现在这两条路都在试，有点焦虑。。

**Comment by TpOut** [comment]
@microshow 哦我知道了。我当时是想，没有编译的话，config.h会不对。
同样的可能还有别的头文件不对（小白的想法）

**Comment by microshow** [comment]
@TpOut  编译的时候它会动态去修改一些文件的，及生成一些新的文件

**Comment by TpOut** [comment]
@microshow 所以我就想跟你要一下编译后的文件嘛。。最开始是这样的。。。因为我想实现编码的代码

**Comment by microshow** [comment]
@TpOut  现在呢？

**Comment by TpOut** [comment]
@microshow

**Comment by sway913** [comment]
要么native开源吧，有问题一起修改吧

**Comment by microshow** [comment]
会的，有些我还在修改。。感谢大家的支持

**Comment by microshow** [comment]
@TpOut ffmpeg-4.0 的include文件已已上传，试试这个？
https://github.com/microshow/RxFFmpeg/tree/master/source/ffmpeg-4.0-include

**Comment by TpOut** [comment]
@microshow 非常感谢了。我再试试。

**Comment by JDDJJ** [comment]
楼主很赞 可以开源一下jni层代码 一起研究研究 我最近也在搞ffmpeg

**Comment by microshow** [comment]
@TpOut include 有解决你的问题吗？

**Comment by TpOut** [comment]
@microshow 惭愧，个把月在补基础，c++和jni 神马的。这两天再研究下

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的

**Comment by sway913** [comment]
> 可以更新V2.0.0版本，速度嗖嗖的

我们需要native源码啊，和现有项目结合，要不然安装包体积又变大了。
