### ISSUE TITLE
关于音频m4a格式的拼接

### ISSUE THREAD

**Issue by WangkeqiangS** [microshow/RxFFmpeg#185]
似乎我们的库不支持对m4a格式的音频进行拼接，请问有什么好的解决办法嘛？

**Comment by microshow** [comment]
支持的，请用完整版

**Comment by WangkeqiangS** [comment]
现在用的就是完整版    似乎不支持对m4a进行拼接

**Comment by WangkeqiangS** [comment]
是 拼   接

**Comment by microshow** [comment]
检查下命令

**Comment by WangkeqiangS** [comment]
ffmpeg

**Comment by WangkeqiangS** [comment]
ffmpeg
-i b.mp3|b.m4a
-acodec copy
-y c.mp3  文件都是存在的  其它格式是正常的  除了wav  似乎ffmpeg库不支持

**Comment by WangkeqiangS** [comment]
已找到解决方法  谢谢大神
wav拼接的解决方法：https://blog.csdn.net/u011285710/article/details/88989062
m4a拼接的解决方法：https://www.jianshu.com/p/9c34570e20c6

**Comment by WangkeqiangS** [comment]
还有一个问题  是否可以同时执行两个命令呢。使用异步可能会出现崩溃的情况
