### ISSUE TITLE
怎么将多个ffmpeg命令合成1个去执行？

### ISSUE THREAD

**Issue by qiaoaimi** [microshow/RxFFmpeg#196]

**Comment by microshow** [comment]
得从你的命令出发，将多个命令用一个命令实现

**Comment by 15726659509** [comment]
新手求指导，该怎么用一个命令实现？比如，我想做两个剪切之后再进行合成的操作。
String txt1 = "ffmpeg -i .../111.mp3 -vn -acodec copy -ss 00:00:00 -t 00:01:00 .../outqian.mp3";
String txt2 = "ffmpeg -i .../111.mp3 -vn -acodec copy -ss 00:01:10 .../outhou.mp3";
String txt3 = "ffmpeg -y -i concat:...\outqian.mp3|...\outhou.mp3" -acodec copy ...\outzong.mp3";

**Comment by microshow** [comment]
建议先去了解下ffmpeg的命令语法

**Comment by qiaoaimi** [comment]
谢谢!
