### ISSUE TITLE
您好，请问这个视频处理库是否支持把视频解码成一帧帧的图片？，谢谢！

### ISSUE THREAD

**Issue by microgogo** [microshow/RxFFmpeg#2]
如题

**Comment by microshow** [comment]
@microgogo  可以的，您可以尝试一下这个命令是把视频解码成一张张图片:  ffmpeg -y -i /storage/emulated/0/1/input.mp4 -preset superfast /storage/emulated/0/1/output_frames_%05d.jpg

**Comment by microgogo** [comment]
@microshow 感谢！！已解决★★★★★

**Comment by tianshaokai** [comment]
希望作者可以添加一些常用的demo，比如 题目的demo非常常用

**Comment by microshow** [comment]
常用命令汇总 https://github.com/microshow/RxFFmpeg/blob/master/preview/docs/cmd.md

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}
