### ISSUE TITLE
您好，在导入到Android Studio 之后包这样的错误，你知道是什么问题吗？

### ISSUE THREAD

**Issue by ELEVENEV** [microshow/RxFFmpeg#20]
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_close: error: undefined reference to 'lame_close'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_frame: error: undefined reference to 'lame_encode_buffer'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_frame: error: undefined reference to 'lame_encode_buffer_int'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_frame: error: undefined reference to 'lame_encode_buffer_float'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_frame: error: undefined reference to 'lame_encode_flush'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_init'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_num_channels'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_mode'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_in_samplerate'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_out_samplerate'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_quality'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_VBR'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_VBR_quality'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_VBR'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_VBR_mean_bitrate_kbps'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_brate'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_bWriteVbrTag'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_set_disable_reservoir'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_init_params'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_get_encoder_delay'
../../../../src/main/jniLibs/armeabi-v7a/libavcodec.a(libmp3lame.o):libmp3lame.c:function mp3lame_encode_init: error: undefined reference to 'lame_get_framesize'

**Comment by microshow** [comment]
没遇到这种错误呀，你直接把这个工程导入到as看会不会出现问题

**Comment by ELEVENEV** [comment]
我是按照您提供的库，然后下载了在自己的虚拟机环境编译的，有问题吗，编译完导入之后就会报这个错，是不是我编译设置有问题，编译也没有报错，
还麻烦您帮忙看一下，谢谢
![image](https://user-images.githubusercontent.com/20473853/54257300-d6594c00-4599-11e9-9f0b-43acb27d8ca9.png)
![image](https://user-images.githubusercontent.com/20473853/54257340-f7ba3800-4599-11e9-9df5-ffdb6f29c69d.png)

**Comment by microshow** [comment]
你这是自己重新编译吗？还以为是直接使用我编译好的so，
可能是你编译的时候哪里没配置好吧

**Comment by ELEVENEV** [comment]
我上面有截图，您有空帮我看看是哪里没有配置好导致的，感谢大神。

**Comment by microshow** [comment]
用的ffmpeg-3.2.5? ,

**Comment by ELEVENEV** [comment]
恩，是的，和ffmpeg的版本会有关系吗？

**Comment by microshow** [comment]
换个版本试试吧，推荐我项目简介里提供的各版本库试下~

**Comment by ELEVENEV** [comment]
好的，我试试

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
