### ISSUE TITLE
找不到文件 (File not found) when running FFmpeg commands

### ISSUE THREAD

**Issue by tatirajurishabh** [microshow/RxFFmpeg#206]
Hi, first of all, thank you for this great library!

I am trying to run the following commands using RxFFmpeg:
`-i /storage/emulated/0/Movies/inshot/InShot_20200927_203143257.mp4 -vf transpose=1,transpose=1 /data/user/0/com.videoplayer/cache/tempRotatedVideo.mp4`

It returns the following message in the callback:
`找不到文件`

I can confirm that storage permissions are provided.

The input file exists and can be accessed by code, which can be confirmed by File.exists(), the code returns "true".

-----
Translated text below, apologies for any mistakes.

嗨，首先，感谢您提供的这个很棒的图书馆！

我正在尝试使用RxFFmpeg运行以下命令：
`-i /storage/emulated/0/Movies/inshot/InShot_20200927_203143257.mp4 -vf transpose=1,transpose=1 /data/user/0/com.videoplayer/cache/tempRotatedVideo.mp4`

它返回以下消息：
`找不到文件`

我可以确认提供了存储权限。

输入文件存在并且可以通过代码访问，可以通过 `File.exists()` 进行确认，代码返回 `true`。

**Comment by microshow** [comment]
ffmpeg -y -i /storage/emulated/0/1/input.mp4 -vf transpose=1,transpose=1 -preset superfast /storage/emulated/0/1/result.mp4
刚试了一下没有问题呢

**Comment by tatirajurishabh** [comment]
@microshow thanks! the extra flags worked.
