### ISSUE TITLE
MOV格式

### ISSUE THREAD

**Issue by Adolphsa** [microshow/RxFFmpeg#21]
支持MOV格式吗

**Comment by microshow** [comment]
你可以试一下

**Comment by Adolphsa** [comment]
不支持  你应该是ffmpeg编译的时候没有选mov的的解码器

**Comment by microshow** [comment]
支持的

ffmpeg -y -i /storage/emulated/0/1/input.mp4 -preset superfast /storage/emulated/0/1/result.mov

或者

ffmpeg -y -i /storage/emulated/0/1/input.mov -preset superfast /storage/emulated/0/1/result.mp4

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
