### ISSUE TITLE
找不到runFFmpegCmd(String[] commands)方法

### ISSUE THREAD

**Issue by Adolphsa** [microshow/RxFFmpeg#22]
我把rxffmpeg当成一个module导入到android studio的工程中测试，运行的时候会报如下的错误：
找不到runFFmpegCmd(java.lang.String[])方法 ，
是我工程的包名不对吗？

03-14 11:44:20.597 2750-11534/com.cheyuncld.auto A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethod called with pending exception 'java.lang.NoSuchMethodError' thrown in int io.microshow.rxffmpeg.RxFFmpegInvoke.runFFmpegCmd(java.lang.String[]):-2
    art/runtime/check_jni.cc:65]     in call to CallVoidMethod
    art/runtime/check_jni.cc:65]     from int io.microshow.rxffmpeg.RxFFmpegInvoke.runFFmpegCmd(java.lang.String[])
    art/runtime/check_jni.cc:65] "RxCachedThreadScheduler-1" daemon prio=5 tid=34 Runnable
    art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x1325ea40 self=0x9f58a800
    art/runtime/check_jni.cc:65]   | sysTid=11534 nice=0 cgrp=apps sched=0/0 handle=0xa21da780
    art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=48 stm=8 core=3 HZ=100
    art/runtime/check_jni.cc:65]   | stack=0x9dc4b000-0x9dc4d000 stackSize=1036KB
    art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
    art/runtime/check_jni.cc:65]   native: #00 pc 000045d4  /system/lib/libbacktrace_libc++.so (_ZN13UnwindCurrent6UnwindEjP8ucontext+23)
    art/runtime/check_jni.cc:65]   native: #01 pc 00002e55  /system/lib/libbacktrace_libc++.so (_ZN9Backtrace6UnwindEjP8ucontext+8)
    art/runtime/check_jni.cc:65]   native: #02 pc 0024029d  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_6mirror9ArtMethodE+68)
    art/runtime/check_jni.cc:65]   native: #03 pc 0022492f  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+146)
    art/runtime/check_jni.cc:65]   native: #04 pc 000afa83  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+582)
    art/runtime/check_jni.cc:65]   native: #05 pc 000b01bd  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+60)
    art/runtime/check_jni.cc:65]   native: #06 pc 000b32cd  /system/lib/libart.so (_ZN3art11ScopedCheckC2EP7_JNIEnviPKc+1284)
    art/runtime/check_jni.cc:65]   native: #07 pc 000ba6ff  /system/lib/libart.so (_ZN3art8CheckJNI14CallVoidMethodEP7_JNIEnvP8_jobjectP10_jmethodIDz+34)
    art/runtime/check_jni.cc:65]   native: #08 pc 000124ff  /data/app/com.cheyuncld.auto-1/lib/arm/libffmpeg-invoke.so (???)
    art/runtime/check_jni.cc:65]   native: #09 pc 0001156f  /data/app/com.cheyuncld.auto-1/lib/arm/libffmpeg-invoke.so (???)
    art/runtime/check_jni.cc:65]   native: #10 pc 0000e0bd  /data/app/com.cheyuncld.auto-1/lib/arm/libffmpeg-invoke.so (run_ffmpeg_command+356)
    art/runtime/check_jni.cc:65]   native: #11 pc 000228df  /data/app/com.cheyuncld.auto-1/lib/arm/libffmpeg-invoke.so (Java_io_microshow_rxffmpeg_RxFFmpegInvoke_runFFmpegCmd+134)
    art/runtime/check_jni.cc:65]   native: #12 pc 000da75f  /data/dalvik-cache/arm/data@app@com.cheyuncld.auto-1@base.apk@classes.dex (Java_io_microshow_rxffmpeg_RxFFmpegInvoke_runFFmpegCmd___3Ljava_lang_String_2+102)
    art/runtime/check_jni.cc:65]   at io.microshow.rxffmpeg.RxFFmpegInvoke.runFFmpegCmd(Native method)
    art/runtime/check_jni.cc:65]   at io.microshow.rxffmpeg.c.a(RxFFmpegInvoke.java:108)
    art/runtime/check_jni.cc:65]   at io.reactivex.internal.operators.flowable.FlowableCreate.d(FlowableCreate.java:71)
    art/runtime/check_jni.cc:65]   at io.reactivex.j.a(Flowable.java:14636)
    art/runtime/check_jni.cc:65]   at io.reactivex.j.subscribe(Flowable.java:14583)
    art/runtime/check_jni.cc:65]   at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
    art/runtime/check_jni.cc:65]   at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
    art/runtime/check_jni.cc:65]   at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
    art/runtime/check_jni.cc:65]   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    art/runtime/check_jni.cc:65]   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
    art/runtime/check_jni.cc:65]   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
    art/runtime/check_jni.cc:65]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    art/runtime/check_jni.cc:65]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    art/runtime/check_jni.cc:65]   at java.lang.Thread.run(Thread.java:818)
    art/runtime/check_jni.cc:65]

**Comment by microshow** [comment]
rxffmpeg这个module的包名不要改动

**Comment by Adolphsa** [comment]
rxffmpeg module一点都没有改动  直接复制进去的。

**Comment by Adolphsa** [comment]
![image](https://user-images.githubusercontent.com/12694208/54341557-0cb7c980-4675-11e9-886e-7f77a835a96a.png)

**Comment by microshow** [comment]
那你直接运行这个demo可以跑吗

**Comment by Adolphsa** [comment]
直接下载你的工程是可以的

**Comment by microshow** [comment]
还是混淆了？

**Comment by Adolphsa** [comment]
我再新建一个工程试试。

**Comment by microshow** [comment]
你工程下除了这个文件夹armeabi-v7a，还有armeabi等文件夹吗？
或检查下编译时是否开启了混淆代码

**Comment by Adolphsa** [comment]
确实是因为混淆的原因  非常感谢。

**Comment by microshow** [comment]
o(*￣︶￣*)o 感谢支持

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
