### ISSUE TITLE
音频视频合并失败

### ISSUE THREAD

**Issue by Jooyer** [microshow/RxFFmpeg#23]
你好,大佬:
     我直接clone了此项目,然后试着提取音频,视频等都正常, 但是在合并音频和视频时报错:
"ffmpeg –i -y " + DIR + "video.mp4" + " –i " + DIR + "tempMusic.aac" + " –vcodec copy –acodec copy " + DIR + "videoMusicAudio.mp4"
,上面是我写的命令,请问是什么问题呢?

**Comment by microshow** [comment]
–vcodec copy –acodec copy 去掉试试

**Comment by Jooyer** [comment]
commands = new String[11];
                commands[0] = "ffmpeg";
                commands[1] = "-i";
                commands[2] = DIR + "video.mp4";
                commands[3] = "-i";
                commands[4] = DIR + "tempMusic.aac";
                commands[5] = "-acodec";
                commands[6] = "copy";
                commands[7] = "-vcodec";
                commands[8] = "copy";
                commands[9] = DIR + "videoMusicAudio.mp4";
                commands[10] = "-y";
这么写可以了!多谢大佬

**Comment by KnnethKong** [comment]
我也遇到了，我是把aac转成mp3了 ，然后mp3和mp4合并成功了

**Comment by microshow** [comment]
如果是aac的话，可以指定-acodec libfdk_aac

**Comment by KnnethKong** [comment]
好的 谢谢

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
