### ISSUE TITLE
crash_dump32: cannot open libmiuindbg.so: No such file or directory

### ISSUE THREAD

**Issue by yangfeng1994** [microshow/RxFFmpeg#24]
将您的model打成aar，执行命令的时候 到百分之91的时候，会报错 crash_dump32: cannot open libmiuindbg.so: No such file or directory

**Comment by microshow** [comment]
libmiuindbg.so 这个是什么？ 
运行demo的时候也会出现那问题吗
您使用的命令是哪个

**Comment by yangfeng1994** [comment]
demo不会出现，将您的库移植到自己的项目中，会出现这个问题，我用的是小米手机，这个应该是会造成找不到小米自己的某个库。如果方便的话，还是希望您能弄成依赖，方便引用，因为移植到自己的项目，总会有未知的异常。

**Comment by microshow** [comment]
可以先参考这种方式试试 https://github.com/microshow/RxFFmpeg/issues/22
你自己打的aar可能没打全

**Comment by yangfeng1994** [comment]
没有混淆，我用的是debug的方式，方法名是能找到的，我把你的项目以model的方式引入，也不行的。就有点迷。

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的

**Comment by tianwenfang2014oe** [comment]
在android11上直接运行demo.apk(直接从GitHub下的)会直接闪退

**Comment by microshow** [comment]
具体日志可以贴一下吗
