### ISSUE TITLE
音频提取提示文件不存在

### ISSUE THREAD

**Issue by just0119** [microshow/RxFFmpeg#249]
String text3 = "ffmpeg -y -i /sdcard/test.mp4 -acodec copy -vn out.mp3";
 String text4 = "ffmpeg -y -i /sdcard/test.mp4 -f image2 -ss 00:00:01 -vframes 1 -preset superfast /sdcard/test.jpg";

提取音频时，上面的命令提示找不到文件，下面的命令可以正常执行

**Comment by just0119** [comment]
输出路径不对。。。

**Comment by chenhaiwork** [comment]
完整命令是什么？
