### ISSUE TITLE
想请问一下，作者使用的ffmpeg中断命令是那个？可以分享一下吗？

### ISSUE THREAD

**Issue by online2** [microshow/RxFFmpeg#25]

**Comment by microshow** [comment]
是在转码的时候，如果调用了RxFFmpegInvoke.getInstance().exit();，就会退出当前执行动作

**Comment by online2** [comment]
> 是在转码的时候，如果调用了RxFFmpegInvoke.getInstance().exit();，就会退出当前执行动作

调这RxFFmpegInvoke.getInstance().exit();这句代码的时候，在ndk层，作者是怎么去中断正在执的ffmpeg任务

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
