### ISSUE TITLE
RxFFmpegPlayer播放器

### ISSUE THREAD

**Issue by Tokyonth** [microshow/RxFFmpeg#255]
问一下播放器支持角度旋转，缩放，倍速吗，貌似没有

**Comment by microshow** [comment]
还在完善

**Comment by Tokyonth** [comment]
RxFFmpegPlayerView是共用或者了啥东西 还是 单例性质，我一个Activity播放，跳到另一个Activity播放，视频源文件不一样，但画面居然是一样的
