### ISSUE TITLE
你好 我这面遇到了一个问题 找不到.so

### ISSUE THREAD

**Issue by wangyikai1234567** [microshow/RxFFmpeg#29]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.wdcloud.luke.courseedit-2/base.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_dependencies_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_0_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_1_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_2_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_3_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_4_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_5_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_6_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_7_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_8_apk.apk", zip file "/data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/user/0/cn.wdcloud.luke.courseedit/files/so, /data/app/cn.wdcloud.luke.courseedit-2/lib/arm64, /data/app/cn.wdcloud.luke.courseedit-2/base.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/cn.wdcloud.luke.courseedit-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libffmpeg-core.so"

**Comment by microshow** [comment]
是通过下载代码的方式依赖，还是通过gradler依赖的方式？

**Comment by microshow** [comment]
目前只提供了v7a平台的so库的

**Comment by wangyikai1234567** [comment]
额额 你好 我这面是通过下载引入的module

**Comment by wangyikai1234567** [comment]
那现在还有处理的办法么？

**Comment by microshow** [comment]
您的项目里应该有arm64-v8a文件夹，rxffmpeg目前只提供了v7a平台库，您可以把您项目里的arm64-v8a目录移除试试？包括很多大型app也是只保留v7a平台的so即可

**Comment by wangyikai1234567** [comment]
好的 谢谢 我先试试

**Comment by renjunjia3** [comment]
通过依赖的方式 还是报这个错

**Comment by microshow** [comment]
@renjunjia3  你项目里面是不是也有arm64-v8a文件夹呢

**Comment by microshow** [comment]
@wangyikai1234567 你的问题解决了吗

**Comment by renjunjia3** [comment]
defaultConfig {
        .
        .
        .
        ndk {
            abiFilters "armeabi-v7a"
        }
    }

这样就行了

**Comment by microshow** [comment]
嗯嗯，因为rxffmpeg目前只提供了v7平台的so，只要吧其它平台的目录删掉即可，包括现在很多大型app也是只保留v7a这个平台的

**Comment by microshow** [comment]
新建了QQ群：799934185  
欢迎加群

**Comment by tianshaokai** [comment]
目前安卓要求适配64位，作者近期会提供吗？

**Comment by microshow** [comment]
已提供64位，欢迎更新2.0.0版本
