### ISSUE TITLE
你好请问两个或则三个视频拼接怎么操作了

### ISSUE THREAD

**Issue by niehuaming** [microshow/RxFFmpeg#3]

**Comment by microshow** [comment]
@niehuaming 
这种合并方式的适用场景是：当容器格式不支持文件层次的合并，而又不想（不需要）进行再编码的操作的时候。这种方式对源视频同样有【同格式同性质】的要求 
ffmpeg -y -f concat -safe 0 -i Cam01.txt -c copy Cam01.mp4

Cam01.txt文件里面的内容类似如下(要改成全路径形式)
file 'input1.mp4'
file 'input2.mp4'
file 'input3.mp4'

**Comment by niehuaming** [comment]
我现在在手机上面操作，我的代码如下
![image](https://user-images.githubusercontent.com/12639114/49778900-650fc000-fd42-11e8-8b17-b8c57f7bb151.png)


然后提示我错误
![image](https://user-images.githubusercontent.com/12639114/49778905-6b9e3780-fd42-11e8-944d-199eed081ea9.png)

**Comment by microshow** [comment]
这个不是我们的apk?  试试ffmpeg -y -f concat -safe 0 -i Cam01.txt -c copy Cam01.mp4

**Comment by microshow** [comment]
@niehuaming V1.2.0版本特性：提升转码效率，重新编译ffmpeg，修复拼接视频出错的bug,支持更多格式，包括支持mp3,aac,wav等格式的音频导出，丰富了更多功能，欢迎更新！

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的

**Comment by chenxiaofei910714** [comment]
> @niehuaming
> 这种合并方式的适用场景是：当容器格式不支持文件格式的合并，选择操作（不需要）进行再编码的时候。的要求
> ffmpeg -y -f concat -safe 0 -i Cam01.txt -c copy Cam01.mp4
> 
> Cam01.txt文件里面的内容类似如下(要改成全路径形式)
> file 'input1.mp4'
> file 'input2.mp4'
> file 'input3.mp4'

这个命令适用于编码、码率、帧率、格式相同，分辨率不同?是能够加快拼接视频速度？
