### ISSUE TITLE
执行命令报错 用的1.2.4

### ISSUE THREAD

**Issue by renjunjia3** [microshow/RxFFmpeg#30]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 29898 (RxCachedThreadS), pid 29813 (ianyi.watermark)

命令：ffmpeg -i /storage/emulated/0/小精灵美化/小精灵美化视频壁纸/201811150354170696656.mp4 -vf delogo=264.901855:477.397644:378.328674:346.023560:1 /data/user/0/com.jianyi.watermark/cache/ffmpeg_out.mp4

**Comment by microshow** [comment]
有更详细的日志吗？路径有没问题・_・?中文路径？

**Comment by microshow** [comment]
你的第三个第四个参数应该超限了，需要根据分辨率去计算合适的宽高，

模糊水印

删除logo

语法：-vf delogo=x:y:w:h[:t[:show]]

x:y 离左上角的坐标

w:h  logo的宽和高

t: 矩形边缘的厚度默认值4   (set delogo area band size，其实是内矩形到外矩形的距离，设置的这个模糊条带可以起到过渡作用，还可以了解到，条带区域的像素会被用来插值运算。参数 band 的值不宜设置过大。)

show：若设置为1有一个绿色的矩形，默认值0.

ffplay -i jidu.mp4 -vf delogo=50:51:60:60:100:0

依次是  左上X坐标，左上Y坐标，宽，高，set delogo area band size， 是否加框。
例子：ffmpeg -i 1.mp4  -vf delogo=40:25:100:30:10:1  a.mp4

**Comment by microshow** [comment]
新建了QQ群：799934185  
欢迎加群

**Comment by renjunjia3** [comment]
命令没问题的 我自己编译的so是可以运行

**Comment by microshow** [comment]
命令应该没啥问题，换个分辨率大点的视频，因为你那宽高可能超过视频尺寸了

**Comment by renjunjia3** [comment]
视频是720*1280的应该是没问题的 我加群了通过一下 给你发日志看下

**Comment by microshow** [comment]
你试下调整参数，看是不是宽高超限了
ffmpeg -y -i /storage/emulated/0/1/input.mp4 -vf delogo=2.901855:2.397644:100.328674:100.023560:1 -preset superfast /storage/emulated/0/1/result.mp4

我这边试了下没问题

**Comment by renjunjia3** [comment]
对照了2个命令，发现是我自己所以的输出文件都是同一个路径。如果目录下已经存在了该文件，执行命令时就会出现问题，所以如果输出路径是同一个的话 ，请在命令加上 -y 就行了。 
ffmpeg -y ...
