### ISSUE TITLE
请问支持字幕添加吗？

### ISSUE THREAD

**Issue by yangfeng1994** [microshow/RxFFmpeg#31]
想问一下，可以添加srt或者ass的字幕文件吗？

**Comment by microshow** [comment]
应该可以，你可以试试

**Comment by yangfeng1994** [comment]
你好，我在demo里面试了一下，是不行的。ffmpeg -threads 0 -i /storage/emulated/0/DCIM/Camera/79da482391d067e86d871ed1028a7c33.mp4 -c:v libx264 -c:a aac -b:a 196k -vf subtitles=/storage/emulated/0/Android/data/2019-04-14-22-09-26_tmpss.srt:force_style='FontName=Arial,FontSize=22,OutlineColour=&H22000000,BorderStyle=3' -f mp4 -preset slow -profile:v baseline -x264opts level=3.0:ref=1 -b:v 2800k -y /storage/emulated/0/DCIM/Camera/123456789.mp4
有时间您可以试一下看看。

**Comment by microshow** [comment]
字幕文件发一下吧，或者加群，把字幕文件上传下

**Comment by yangfeng1994** [comment]
以加群，你那边同意一下，我发群里，因为这个字幕文件，我用电脑的ffmpeg 是能添加进去的。
