### ISSUE TITLE
请问适配android 8.0+版本吗

### ISSUE THREAD

**Issue by heping56** [microshow/RxFFmpeg#32]
以前自己在项目中用了ffmpeg的so库，后来android7.0以上的系统就会报错，好像是说so的编译方式有问题，请问您的这个视频了android新系统版本吗？

**Comment by microshow** [comment]
支持8.0+的， 你可以自己跑下demo

**Comment by microshow** [comment]
可以更新V2.o.o版本，做了很多改进
