### ISSUE TITLE
压缩3840*2160高清视频报错，没啥报错信息直接崩溃。

### ISSUE THREAD

**Issue by bigmanLau** [microshow/RxFFmpeg#33]
![image](https://user-images.githubusercontent.com/24562273/56260662-a9ed9e00-610a-11e9-9b71-3ad8e1888fc1.png)
压缩3840*2160高清视频报错，没啥报错信息直接崩溃。

**Comment by microshow** [comment]
＃27  参考下

**Comment by sansCL** [comment]
> ＃27 参考下

最新版1.2.4还是崩溃哦  加了ffmpeg -threads 2 -y -i 暂时解决

**Comment by protectedMan** [comment]
同此问题
