### ISSUE TITLE
添加gif卡到100%不动了，视频也不能播放，大神用的哪个命令

### ISSUE THREAD

**Issue by liupengfei666** [microshow/RxFFmpeg#35]
ffmpeg -y -i input.mp4 -ignore_loop 0 -i input.gif -filter_complex [0:v]scale=iw:ih[outv0];[1:0]scale=100.0:50.0[outv1];[outv0][outv1]overlay=10:10:shortest=1 -preset superfast output.mp4

**Comment by microshow** [comment]
加个 -t 你的视频时间

**Comment by liupengfei666** [comment]
> 加个 -t 你的视频时间

加-t后测试可行，但是gif图不动，我用这个命令在别的sdk测试都是可以动的，是我哪儿出问题了么。顺便问一下您在编译ffmpeg的时候有没有做过什么特别的处理

**Comment by microshow** [comment]
你检查下命令……

**Comment by microshow** [comment]
ffmpeg -y -i /storage/emulated/0/1/input.mp4 -ignore_loop 0 -i /storage/emulated/0/1/1.gif -filter_complex [0:v]scale=iw:ih[outv0];[1:0]scale=100.0:50.0[outv1];[outv0][outv1]overlay=10:10:shortest=1 -t 10 -preset superfast /storage/emulated/0/1/out.mp4

我试了一下，没问题哦，或者你换个gif图试试？

**Comment by liupengfei666** [comment]
好的

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
