### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [microshow/RxFFmpeg#36]
这个可以加广告吗，还有这个如果是网络视频 是地址 怎么处理呢 直接把本地换成网络地址吗

**Comment by microshow** [comment]
你指的广告是怎样的呢？网络视频你可以基于这个库去编写c++代码去解码网络视频进行播放

**Comment by TrueloveSomeGIRl** [comment]
就是视频开头有段广告 播放完进去视频 我想的是用画中画添加进去

**Comment by microshow** [comment]
直接拼接就可以啊
