### ISSUE TITLE
视频裁剪速度很慢

### ISSUE THREAD

**Issue by liupengfei666** [microshow/RxFFmpeg#38]
感觉视频裁剪比我自己编译的库还慢，作者能否解答下，我感觉不应该这么慢的。下面是我用的命令ffmpeg -y -i input.mp4 -ss 0 -t 20 output.mp4

**Comment by microshow** [comment]
-vcodec copy

**Comment by microshow** [comment]
-preset superfast

**Comment by liupengfei666** [comment]
> -vcodec copy

加上这个之后超快，但是进度就显示了一个42%然后就完成了~.~

**Comment by liupengfei666** [comment]
谢谢

**Comment by microshow** [comment]
是这样的

**Comment by microshow** [comment]
接入RxFFmpeg的APP方便可以留下联系方式，APP名称+应用商店下载地址，（按登记顺序排序)，啦啦啦
https://github.com/microshow/RxFFmpeg/issues/37
