### ISSUE TITLE
用delogo命令好慢

### ISSUE THREAD

**Issue by hukejia** [microshow/RxFFmpeg#41]
ffmpeg -i  /storage/emulated/0/DouyinQuick/@Mc天勤(v0300f100000bj8rla5b34ar9veh3lug).mp4 -vf delogo=1:1:100:100:0 /storage/emulated/0/Download/haha.mp4
这个命令10秒的视频耗时1分钟，本来就这么慢还是命令有问题呢，有什么办法优化没

**Comment by microshow** [comment]
添加个 -preset superfast 试试

**Comment by hukejia** [comment]
> 添加个 -preset superfast 试试

我刚用这个库FFmpeg-Android，同一个视频20秒，相差了40秒

**Comment by hukejia** [comment]
> 添加个 -preset superfast 试试

具体怎么加啊，我这方面小白

**Comment by microshow** [comment]
ffmpeg -y -i /storage/emulated/0/DouyinQuick/@mc天勤(v0300f100000bj8rla5b34ar9veh3lug).mp4 -vf delogo=1:1💯100:0 -preset superfast /storage/emulated/0/Download/haha.mp4

**Comment by hukejia** [comment]
> ffmpeg -y -i /storage/emulated/0/DouyinQuick/@mc天勤(v0300f100000bj8rla5b34ar9veh3lug).mp4 -vf delogo=1:1💯100:0 -preset superfast /storage/emulated/0/Download/haha.mp4

加之前55秒，加了之后速度是15秒
另一个库，加之前20秒，加之后10秒，麻烦大神看下什么原因导致的呢，毕竟那库不怎么维护了

**Comment by microshow** [comment]
欢迎更新2.0版本  做了性能优化
