### ISSUE TITLE
Supporting arm64-v8a

### ISSUE THREAD

**Issue by nqkwey** [microshow/RxFFmpeg#44]
Could you please add support to arm64-v8a as required here: https://developer.android.com/distribute/best-practices/develop/64-bit?

**Comment by microshow** [comment]
Follow-up support

**Comment by basillee** [comment]
期待作者早日提供，辛苦。

**Comment by microshow** [comment]
近期会提供arm-v8a的支持，感谢大家支持！

**Comment by microshow** [comment]
已支持arm64-v8a， 欢迎升级至V2.0.0版本
