### ISSUE TITLE
图片到视频中速度过慢

### ISSUE THREAD

**Issue by budou1994** [microshow/RxFFmpeg#46]
你好，直接使用这个库的时候，再往视频中添加图片感觉过于慢了，一个10m的视频编辑完成需要一分钟，不知道是否是正常？请教一下。
下面是使用的FFmpeg命令：
`  ffmpeg -i videoPath -i imagePath -filter_complex overlay=0:0 -vcodec libx264 -profile:v baseline -preset ultrafast -b:v 3000k -g 30 -f mp4 outPath`

**Comment by microshow** [comment]
preset superfast 试试这个
