### ISSUE TITLE
您好，请问下连续执行多个命令会导致程序crash吗

### ISSUE THREAD

**Issue by xiagea** [microshow/RxFFmpeg#48]
现在视频添加bgm，先音频裁剪成视频长度，然后音视频混合，第一次完成这个步骤很快，几乎瞬间完成，如果继续执行第二次，程序就会崩溃，log也看不出啥问题。如果第二次隔一段时间运行，不会崩溃，没明白是为什么，希望您能指导下

**Comment by microshow** [comment]
不能同时执行多条命令哦  建议延迟一下处理

**Comment by xiagea** [comment]
> 不能同时执行多条命令哦 建议延迟一下处理

大神能不能优化下，或者有没有别的解决办法

**Comment by microshow** [comment]
可以开多个进程去执行
