### ISSUE TITLE
由于看不到ndk的源码, 所以有个问题请教

### ISSUE THREAD

**Issue by alexliyu7352** [microshow/RxFFmpeg#5]
你这里的应该也是修改了ffmpeg.c实现的cmd命令功能吧?
我想请教下, 如果多个线程执行. 怎么保证线程安全呢?
因为我看ffmpeg.c这个文件里面的main实际上并不是线程安全的, 
也就是在java层只能阻塞调用或者队列调用命令.
没办法一次执行多个命令.是么?

**Comment by alexliyu7352** [comment]
java层多个进程, 还是直接在native层 fork出来

**Comment by alexliyu7352** [comment]
其实还是最好多线程实现, 因为多进程太重了, 况且android就算java层也有限制.
但是不知道如何多线程实现, 看来不能直接使用ffmpeg.c, 必须要自己重新封装transcode的代码.
也只有这个办法是么?

**Comment by microshow** [comment]
其实有试过在ndk层多线程去实现，但中断当前命令不太好优雅的中断，而且会引发比较多的问题

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
