### ISSUE TITLE
视频压缩到10%直接闪退，提供原视频

### ISSUE THREAD

**Issue by protectedMan** [microshow/RxFFmpeg#51]
原视频链接
https://su.bcebos.com/v1/cloudshop-test/测试视频ios-iphonex.mp4
使用demo测试闪退
压缩命令为：
ffmpeg -y -i /storage/emulated/0/DCIM/Camera/测试视频ios-iphonex.mp4 -b 2097k -r 30 -vcodec libx264 -preset superfast /storage/emulated/0/DCIM/Camera/测试视频ios-iphonex1.mp4

**Comment by microshow** [comment]
视频下不了，你的视频分辨率是多大的呢？换个视频也会出现吗？

**Comment by protectedMan** [comment]
我试了，这个视频地址没问题的啦。
这个分辨率是4k的

**Comment by microshow** [comment]
4k视频 先对视频进行缩放

**Comment by tianshaokai** [comment]
这个视频根本看不见图像

**Comment by protectedMan** [comment]
> 这个视频根本看不见图像

请使用下载器下载，并且使用支持h265的视频播放器进行播放。
