### ISSUE TITLE
No such filter: '"scale'

### ISSUE THREAD

**Issue by protectedMan** [microshow/RxFFmpeg#53]
压缩命令如下
binding.editText.setText("ffmpeg " +
                "-y -i /storage/emulated/0/DCIM/Camera/测试视频ios-iphonex.mp4 " +
                "-b:v 2097k " +
                "-vcodec libx264 " +
                //"-vf \"scale='min(1920, iw)':'-1'\" " +  //如果小于宽度1920，就不动分辨率，如果宽度大于1920就缩小到1920。scale的用法很灵活，具体参考https://trac.ffmpeg.org/wiki/Scaling
                "-vf \"scale='min(1920,iw)':'-1'\" " +
                "-preset superfast /storage/emulated/0/DCIM/Camera/测试视频ios-iphonex1.mp4");

**Comment by microshow** [comment]
ffmpeg -y -i /storage/emulated/0/1/input.mp4 -b:v 2079k -vcodec libx264 -vf scale=320:320 -preset superfast /storage/emulated/0/1/result.mp4

**Comment by protectedMan** [comment]
我这边在项目内集成调用直接闪退，跟ffmpeg相关的日志就只有这些
![image](https://user-images.githubusercontent.com/17565737/60313504-fb7b9a00-9991-11e9-9cd8-24b7f14566a0.png)
