### ISSUE TITLE
给视频添加水印，进度最终停在99不动

### ISSUE THREAD

**Issue by KinaZhen** [microshow/RxFFmpeg#55]
执行添加水印命令 ：ffmpeg -y -i /Movies/1561687833867015.mp4 -i /water/graffiti.png -filter_complex [0:v]scale=iw:ih[outv0];[1:0]scale=536.0:712.0[outv1];[outv0][outv1]overlay=0:0 -preset superfast /storage/emulated/0/VideoEditor/1562119724572.mp4

执行进度停在99，但是实际已经完成

**Comment by microshow** [comment]
ffmpeg -y -i /storage/emulated/0/1/input.mp4 -i /storage/emulated/0/1/1.png -filter_complex [0:v]scale=iw:ih[outv0];[1:0]scale=536.0:712.0[outv1];[outv0][outv1]overlay=0:0 -preset superfast /storage/emulated/0/1/1562119724572.mp4

刚试了一下 操作正常啊 可以执行完成

**Comment by KinaZhen** [comment]
> ffmpeg -y -i /storage/emulated/0/1/input.mp4 -i /storage/emulated/0/1/1.png -filter_complex [0:v]scale=iw:ih[outv0];[1:0]scale=536.0:712.0[outv1];[outv0][outv1]overlay=0:0 -preset superfast /storage/emulated/0/1/1562119724572.mp4
> 
> 刚试了一下 操作正常啊 可以执行完成

我这边执行多次都是定在99，debug，没有走到finish

**Comment by microshow** [comment]
换个视频  换个水印呢？

**Comment by KinaZhen** [comment]
> 换个视频 换个水印呢？

找到问题所在，处理rxjava逻辑时出了个问题，  谢谢回复！
