### ISSUE TITLE
是否可以生成一个arm的so文件

### ISSUE THREAD

**Issue by Jamie-gilbert** [microshow/RxFFmpeg#56]
哥哥，您的生成的so文件，能不能生产成一个arm的呀。

**Comment by microshow** [comment]
你把v7a的放到arm能用吗

**Comment by Jamie-gilbert** [comment]
好的，哥哥，我这边试一下

**Comment by microshow** [comment]
近期会完善v7a和v8a平台的so库，arm可能要废弃了，建议使用v7a平台~

**Comment by Jamie-gilbert** [comment]
哥哥，请教您一个问题，图片用指令生成的MP4文件，如何与手机拍摄生成的MP4
文件进行无损合并，ffmpeg中有相关的命令吗。求大神执教

**Comment by microshow** [comment]
https://github.com/microshow/RxFFmpeg/blob/master/preview/docs/cmd.md

**Comment by Jamie-gilbert** [comment]
好的，哥哥，我们这边看一下，多谢多谢
