### ISSUE TITLE
FFmpeg 4.0 + X264 + mp3lame + fdk-aac的编译过程

### ISSUE THREAD

**Issue by stormdzh** [microshow/RxFFmpeg#6]
您好，请问您可把你的编译脚本贡献出来吗？我想自己编译个ffmpeg，让ffmpeg里面有mp3lame和mp3lame和X264。

**Comment by microshow** [comment]
这个后续相对完善稳定后，编译脚本及JNI层代码，全部开源。

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
