### ISSUE TITLE
无声音的视频文件,在分离视频和音频的时候crash

### ISSUE THREAD

**Issue by chenxihoulang** [microshow/RxFFmpeg#70]
TAG_FFMPEG: Output file #0 does not contain any stream

**Comment by microshow** [comment]
建议在java层先判断视频有没音轨，在执行命令，可以用这个方法判断 https://github.com/microshow/RxFFmpeg/blob/master/rxffmpeg/src/main/java/io/microshow/rxffmpeg/AudioVideoUtils.java   selectAudioTrack(MediaExtractor extractor)
