### ISSUE TITLE
Getting this crash when loading the app in emulator and in some android devices.

### ISSUE THREAD

**Issue by Harshjain2094** [microshow/RxFFmpeg#74]
Here is the crash log.

> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.clouthub.clouthub-auHa4rtqDMagU1r7iMtW9Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.clouthub.clouthub-auHa4rtqDMagU1r7iMtW9Q==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "librxffmpeg-core.so"

**Comment by microshow** [comment]
demo apk 会出现这个问题吗

**Comment by Harshjain2094** [comment]
Demo Apk that you have provided in the preview folder? That is not installing it shows APK installed failed.

**Comment by microshow** [comment]
我这边暂时没遇到这种问题，请问您的机型是哪款？

**Comment by Harshjain2094** [comment]
I am facing the problem in the android emulator Pixel_XL_API_26

**Comment by microshow** [comment]
模拟器上没有x86的so可能运行不了，建议在真机上运行

**Comment by Harshjain2094** [comment]
If any real device is running on x86 image then what should be the wayaround it.

**Comment by microshow** [comment]
试试
defaultConfig {
    .
    .
    .
    ndk {
        abiFilters "armeabi-v7a"
    }
}

**Comment by Harshjain2094** [comment]
And also sometimes due to file path or wrong command of ffmpeg it crashes the app, although it should show the error in the onError callback but instead it just crashes. Is there any way it could be fixed.

**Comment by Harshjain2094** [comment]
> 试试
> defaultConfig {
> .
> .
> .
> ndk {
> abiFilters "armeabi-v7a"
> }
> }

Did with this.

ndk {
            abiFilters "armeabi-v7a","arm64-v8a"
        }

**Comment by damaisubimawanto** [comment]
In case if someone is still facing the same problem, you should add `"armeabi"` in abiFilters in app-level build.gradle file for enable running in emulator.

```
defaultConfig {
    ndk {
        abiFilters "armeabi-v7a","armeabi","arm64-v8a","x86","x86_64"
    }
}
```

Have a nice day!
