### ISSUE TITLE
AVI 转码失败

### ISSUE THREAD

**Issue by mendax92** [microshow/RxFFmpeg#9]
大神求指教 ，转到一半就失败了

cmd = {CmdList@4212}  size = 4
 0 = "ffmpeg"
 1 = "-i"
 2 = "/storage/emulated/0/DCIM/Camera/REC_1547559797_0.avi"
 3 = "/storage/emulated/0/rxdrone/outPath/1547625392672.mp4"

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 17292 (RxCachedThreadS)

**Comment by microshow** [comment]
我刚试了下，avi 和mp4互转都没问题哦   或者你换个视频试试

**Comment by microshow** [comment]
ffmpeg -y -i /storage/emulated/0/1/test.avi -max_muxing_queue_size 1024 /storage/emulated/0/1/result.mp4  下载了你的视频 可以转码成功

**Comment by mendax92** [comment]
我拉你最新的代码试试

**Comment by mendax92** [comment]
是我指令写错了~~  多谢了
大神什么时候把编译脚本 上传啊 ？

**Comment by microshow** [comment]
后续相对完善稳定后，编译脚本及JNI层代码，全部上传。

**Comment by microshow** [comment]
可以使用Gradle依赖:)
dependencies {
    implementation 'com.github.microshow:RxFFmpeg:1.2.2'
}

**Comment by microshow** [comment]
可以更新V2.0.0版本，速度嗖嗖的
